#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-unidecode
Version  : 1.3.4
Release  : 40
URL      : https://files.pythonhosted.org/packages/41/16/ee78864c2c2ba9bddba3978baa378f83270c8b7810eb7900f84e62a9ffac/Unidecode-1.3.4.tar.gz
Source0  : https://files.pythonhosted.org/packages/41/16/ee78864c2c2ba9bddba3978baa378f83270c8b7810eb7900f84e62a9ffac/Unidecode-1.3.4.tar.gz
Summary  : ASCII transliterations of Unicode text
Group    : Development/Tools
License  : GPL-2.0
Requires: pypi-unidecode-bin = %{version}-%{release}
Requires: pypi-unidecode-license = %{version}-%{release}
Requires: pypi-unidecode-python = %{version}-%{release}
Requires: pypi-unidecode-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(py)
BuildRequires : pypi-pluggy
BuildRequires : pypi-pytest
BuildRequires : pypi-tox
BuildRequires : pypi-virtualenv

%description
=======================================================
        
        It often happens that you have text data in Unicode, but you need to
        represent it in ASCII. For example when integrating with legacy code that
        doesn't support Unicode, or for ease of entry of non-Roman names on a US
        keyboard, or when constructing ASCII machine identifiers from human-readable
        Unicode strings that should still be somewhat intelligible. A popular example
        of this is when making an URL slug from an article title.
        
        **Unidecode is not a replacement for fully supporting Unicode for strings in
        your program. There are a number of caveats that come with its use,
        especially when its output is directly visible to users. Please read the rest
        of this README before using Unidecode in your project.**
        
        In most of examples listed above you could represent Unicode characters as
        ``???`` or ``\\15BA\\15A0\\1610``, to mention two extreme cases. But that's
        nearly useless to someone who actually wants to read what the text says.

%package bin
Summary: bin components for the pypi-unidecode package.
Group: Binaries
Requires: pypi-unidecode-license = %{version}-%{release}

%description bin
bin components for the pypi-unidecode package.


%package license
Summary: license components for the pypi-unidecode package.
Group: Default

%description license
license components for the pypi-unidecode package.


%package python
Summary: python components for the pypi-unidecode package.
Group: Default
Requires: pypi-unidecode-python3 = %{version}-%{release}

%description python
python components for the pypi-unidecode package.


%package python3
Summary: python3 components for the pypi-unidecode package.
Group: Default
Requires: python3-core
Provides: pypi(unidecode)

%description python3
python3 components for the pypi-unidecode package.


%prep
%setup -q -n Unidecode-1.3.4
cd %{_builddir}/Unidecode-1.3.4
pushd ..
cp -a Unidecode-1.3.4 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1656364313
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
PYTHONPATH=%{buildroot}$(python -c "import sys; print(sys.path[-1])") python setup.py test
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 setup.py build

popd
%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-unidecode
cp %{_builddir}/Unidecode-1.3.4/LICENSE %{buildroot}/usr/share/package-licenses/pypi-unidecode/4cc77b90af91e615a64ae04893fdffa7939db84c
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 -tt setup.py build install --root=%{buildroot}-v3
popd
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/unidecode

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-unidecode/4cc77b90af91e615a64ae04893fdffa7939db84c

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
