#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : Unidecode
Version  : 1.0.23
Release  : 2
URL      : https://files.pythonhosted.org/packages/9b/d8/c1b658ed7ff6e63a745eda483d7d917eb63a79c59fcb422469b85ff47e94/Unidecode-1.0.23.tar.gz
Source0  : https://files.pythonhosted.org/packages/9b/d8/c1b658ed7ff6e63a745eda483d7d917eb63a79c59fcb422469b85ff47e94/Unidecode-1.0.23.tar.gz
Summary  : ASCII transliterations of Unicode text
Group    : Development/Tools
License  : GPL-2.0
Requires: Unidecode-bin = %{version}-%{release}
Requires: Unidecode-license = %{version}-%{release}
Requires: Unidecode-python = %{version}-%{release}
Requires: Unidecode-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3

%description
Unidecode, lossy ASCII transliterations of Unicode text
=======================================================

%package bin
Summary: bin components for the Unidecode package.
Group: Binaries
Requires: Unidecode-license = %{version}-%{release}

%description bin
bin components for the Unidecode package.


%package license
Summary: license components for the Unidecode package.
Group: Default

%description license
license components for the Unidecode package.


%package python
Summary: python components for the Unidecode package.
Group: Default
Requires: Unidecode-python3 = %{version}-%{release}
Provides: unidecode-python

%description python
python components for the Unidecode package.


%package python3
Summary: python3 components for the Unidecode package.
Group: Default
Requires: python3-core

%description python3
python3 components for the Unidecode package.


%prep
%setup -q -n Unidecode-1.0.23

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1547137156
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
PYTHONPATH=%{buildroot}/usr/lib/python3.7/site-packages python3 setup.py test
%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/Unidecode
cp LICENSE %{buildroot}/usr/share/package-licenses/Unidecode/LICENSE
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/unidecode

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/Unidecode/LICENSE

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
